name: test
desc: test
runbooks:
- name: test
  desc: test
  selectors:
  - type: labelSelector
    selector: k8s-app=kube-dns
  - type: labelSelector
    selector: pod-template-hash=7745f9f87f
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.kind}=Pod'
  - type: jsonPathSelector
    selector: '{.metadata.name}=coredns-7745f9f87f-98hpf'
  - type: jsonPathSelector
    selector: '{.metadata.namespace}=kube-system'
  doc: test.md
